version: '3'

services:
  api:
    image: clean-app:latest
    expose:
      - "${WEB_SERVER_PORT}"
      - "${GRPC_SERVER_PORT}"
      - "${GRAPHQL_SERVER_PORT}"
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
      - "${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_started

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306
    volumes:
      - ./database_populate:/docker-entrypoint-initdb.d:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 5s
      timeout: 30s
      retries: 5
